name: yafa_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  numberpicker: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  csv: ^6.0.0
  file_picker: ^8.0.3
  flutter_file_dialog: ^3.0.2
  confirm_dialog: ^1.0.3
  tuple: ^2.0.2
  time_machine: ^0.9.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/muscles/
    - csv/
