name: Gymli
description: "Hypertrophy Helper"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  get_it: ^7.6.4
  flutter_riverpod: ^2.6.1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  go_router: ^14.2.7
  numberpicker: ^2.1.2
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0
  flutter_native_splash: ^2.4.6
  intl: any
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  csv: ^6.0.0
  file_picker: ^8.0.3
  flutter_file_dialog: ^3.0.2
  confirm_dialog: ^1.0.3
  tuple: ^2.0.2
  time_machine: ^0.9.17
  flutter_timer_countdown: ^1.0.7
  shared_preferences: ^2.3.4
  path_provider: ^2.1.3
  rename_app: ^1.3.2
  auth0_flutter: ^1.10.0
  http: ^1.2.2
  table_calendar: ^3.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/muscles/
    - images/drawerlogo/
    - csv/
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/logo.jpeg"
    #background_color: "#hexcode"
    #theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/logo.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/logo.jpeg"